[workspace]
resolver = "2"
members = [
    "ruff_text_size", "compiler/ast", "compiler/core", "compiler/parser", "common"
]

[workspace.dependencies]
ahash = "0.7.6"
anyhow = "1.0.45"
ascii = "1.0"
atty = "0.2.14"
bincode = "1.3.3"
bitflags = "1.3.2"
bstr = "0.2.17"
cfg-if = "1.0"
chrono = "0.4.19"
crossbeam-utils = "0.8.9"
flame = "0.2.2"
glob = "0.3"
hex = "0.4.3"
indexmap = "1.8.1"
insta = "1.14.0"
itertools = "0.10.3"
libc = "0.2.133"
log = "0.4.16"
nix = "0.26"
num-complex = "0.4.0"
num-bigint = "0.4.3"
num-integer = "0.1.44"
num-rational = "0.4.0"
num-traits = "0.2"
num_enum = "0.5.7"
once_cell = "1.13"
parking_lot = "0.12"
paste = "1.0.7"
rand = "0.8.5"
rustyline = "11"
serde = "1.0"
schannel = "0.1.19"
static_assertions = "1.1"
syn = "1.0.91"
thiserror = "1.0"
thread_local = "1.1.4"
unicode_names2 = { version = "0.6.0", git = "https://github.com/youknowone/unicode_names2.git", rev = "4ce16aa85cbcdd9cc830410f1a72ef9a235f2fde" }
widestring = "0.5.1"

[profile.dev.package."*"]
opt-level = 3

[profile.test]
opt-level = 3
# https://github.com/rust-lang/rust/issues/92869
# lto = "thin"

[profile.bench]
lto = "thin"
codegen-units = 1
opt-level = 3

[profile.release]
lto = "thin"
